apiVersion: v1
kind: Service
metadata:
  name: sunhare-digital-marketing
spec:
  selector:
    app: sunhare-digital-marketing-web-02  # Ensure this label matches the label on the target Pod or Deployment
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 443
      targetPort: 3443
      protocol: TCP
      name: https
  type: ClusterIP